name: CI (format & lint)

on:
  pull_request:
    paths:
      - "**.py"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - ".github/workflows/**"
      - "src/**"
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit (all files on PR)
        run: pre-commit run --all-files
