name: Ingestion CI (lint + noop run)

on:
  pull_request:
    paths:
      - "src/profitscout_ingestion/**"
      - ".github/workflows/ingestion-ci.yaml"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
      - "Makefile"
  push:
    branches: [ main ]
    paths:
      - "src/profitscout_ingestion/**"
      - ".github/workflows/ingestion-ci.yaml"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
      - "Makefile"

jobs:
  lint-and-noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit (Black/Ruff)
        run: pre-commit run --all-files

      - name: Noop runner smoke test
        run: |
          python -m profitscout_ingestion.jobs.runner --pipeline noop
