name: Ingestion CI (lint + stub runs)

on:
  pull_request:
    paths:
      - "src/profitscout_ingestion/**"
      - ".github/workflows/ingestion-ci.yaml"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
      - "Makefile"
  push:
    branches: [ main ]
    paths:
      - "src/profitscout_ingestion/**"
      - ".github/workflows/ingestion-ci.yaml"
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
      - "Makefile"

jobs:
  lint:
    env:
      PYTHONPATH: src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit (Black/Ruff)
        run: pre-commit run --all-files

  smoke:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        pipeline: [noop, prices, options, calendar]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run stub
        run: |
          python -m profitscout_ingestion.jobs.runner --pipeline ${{ matrix.pipeline }} --run-date $(date +%F)
